// Login actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";

// sign up actions
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";

// server actions
export const SERVER_CALL_FAILED = "SERVER_CALL_FAILED";

// Logout actions
export const LOGOUT_USER  = 'LOGOUT_USER';
export const LOGOUT_USER_SERVER_RESPONSE_SUCCESS = 'LOGOUT_USER_SERVER_RESPONSE_SUCCESS';
export const SERVER_REPONSE_ERROR = 'SERVER_REPONSE_ERROR';
export const LOGOUT_USER_SERVER_REPONSE_ERROR = 'LOGOUT_USER_SERVER_REPONSE_ERROR';

// Token related

export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';

// firebase database related 

export const SIGNUP_SAVE_DATABASE = "SIGNUP_SAVE_DATABASE";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS = "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR = "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

// Employee firebase database related 

export const EMPLOYEE_SAVE_DATABASE = "EMPLOYEE_SAVE_DATABASE";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS = "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR = "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

// Get Data from Employee Firebase

export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_LIST_SUCCESS_RESPONSE = "GET_EMPLOYEE_LIST_SUCCESS_RESPONSE";
export const GET_EMPLOYEE_LIST_ERROR_RESPONSE = "GET_EMPLOYEE_LIST_ERROR_RESPONSE";

// Employee Info firebase database related 

export const EMPLOYEE_INFO_SAVE_DATABASE = "EMPLOYEE_INFO_SAVE_DATABASE";
export const EMPLOYEE_INFO_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS = "EMPLOYEE_INFO_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const EMPLOYEE_INFO_SAVE_DATABASE_SERVER_RESPONSE_ERROR = "EMPLOYEE_INFO_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

// Task Details
export const GET_TASK_BY_EMPID = "GET_TASK_BY_EMPID";