// Login actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";

// sign up actions
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";

// server actions
export const SERVER_CALL_FAILED = "SERVER_CALL_FAILED";

// Logout actions
export const LOGOUT_USER  = 'LOGOUT_USER';
export const LOGOUT_USER_SERVER_RESPONSE_SUCCESS = 'LOGOUT_USER_SERVER_RESPONSE_SUCCESS';
export const SERVER_REPONSE_ERROR = 'SERVER_REPONSE_ERROR';
export const LOGOUT_USER_SERVER_REPONSE_ERROR = 'LOGOUT_USER_SERVER_REPONSE_ERROR';

// Token related

export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';